events/urls.py
from django.urls import path, include

from events.views import (
    EventCreateView,
    EventListView,
    EventDetailView,
    MyEventListView,
    EventDeleteView,
    EventUpdateView,
    get_my_events
)

urlpatterns = [
    path(
        'new/',
        include([
            path(
                '',
                EventCreateView.as_view(),
                name="events-create"
            ),
            path(
                'group/<int:pk>',
                EventCreateView.as_view(),
                name="events-create-group"
            )
        ])
    ),
    path('<int:pk>', EventDetailView.as_view(), name='events-detail'),
    path('', EventListView.as_view(), name='events-list'),
    path('my/', MyEventListView.as_view(), name='events-my'),
    path('<int:pk>/update', EventUpdateView.as_view(), name='events-update'),
    path('<int:pk>/delete', EventDeleteView.as_view(), name='events-delete'),
    path('get_my_events/', get_my_events, name='get_my_events')

]

gdziejestgrane/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from gdziejestgrane import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('events/', include('events.urls')),
    path('groups/', include('groups.urls')),
    path('localizations/', include('localizations.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

localizations/urls.py
from django.urls import path

from localizations.views import (
    LocalizationCreateView,
    LocalizationListView,
    MyLocalizationListView,
    LocalizationDetailView,
    LocalizationAddressCreateView,
    CommentUpdateView,
    CommentDeleteView
)

urlpatterns = [
    path('new', LocalizationCreateView.as_view(),
         name='localizations-create'),
    path('', LocalizationListView.as_view(),
         name='localizations-list'),
    path('<int:pk>', LocalizationDetailView.as_view(),
         name='localizations-detail'),
    path('my', MyLocalizationListView.as_view(),
         name='localizations-my'),
    path('<int:pk>/address/', LocalizationAddressCreateView.as_view(),
         name='localizations-address-create'),
    path('comment/<int:pk>/update',
         CommentUpdateView.as_view(), name='comment-update'),
    path('comment/<int:pk>/delete',
         CommentDeleteView.as_view(), name='comment-delete')

]

localizations/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from accounts.models import User

SPORT_TYPES = [
    ('football', _('Piłka nożna')),
    ('basketball', _('Koszykówka')),
    ('volleyball', _('Siatkówka')),
    ('tenis', _('Tenis ziemny'))
]


class Localization(models.Model):
    sport_types = SPORT_TYPES
    name = models.CharField(
        max_length=64,
        verbose_name=_('Nazwa')
    )
    sport_type = models.CharField(
        max_length=32,
        choices=sport_types,
        verbose_name=_('Sport')
    )
    localization_url = models.URLField(verbose_name=_('Link'))
    likes = models.ManyToManyField(
        User,
        verbose_name=_('Polubienia')
    )
    picture = models.ImageField(
        default= "localization.png",
        verbose_name=_('Zdjęcie')
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(
            'localizations-detail',
            kwargs={'pk': self.id}
        )


class Comment(models.Model):
    user = models.ForeignKey(
        User,
        related_name='comments',
        on_delete=models.CASCADE
    )
    localization = models.ForeignKey(
        Localization,
        related_name='comments',
        on_delete=models.CASCADE,
        default=1
    )
    content = models.CharField(
        max_length=1000,
        blank=False,
        null=False
    )
    date_created = models.DateTimeField(default=timezone.now)


class LocalizationAddress(models.Model):
    city = models.CharField(max_length=20)
    street = models.CharField(max_length=50)
    house_number = models.CharField(max_length=10)
    postcode = models.CharField(max_length=8)
    lat = models.CharField(max_length=8)
    lon = models.CharField(max_length=8)
    localization = models.OneToOneField(
        Localization,
        on_delete=models.CASCADE,
        verbose_name=_('Obiekt'),
    )

    def __str__(self):
        return f'{self.street} {self.house_number}, {self.postcode} {self.city}'

localizations/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from localizations.models import Comment, LocalizationAddress


class LocalizationAddressForm(forms.ModelForm):
    class Meta:
        model = LocalizationAddress
        fields = [
            'city',
            'street',
            'house_number',
            'postcode']
        labels = {
            'city': _("Miejscowość"),
            'street': _("Ulica"),
            'house_number': _('Numer domu'),
            'postcode': _('Kod pocztowy')
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

    content = forms.CharField(
        label=_("Treść komentarza"),
        required=True,
        widget=forms.Textarea(
            attrs={
                'cols': 80,
                'rows': 4,
                'style': 'resize:none;'
            }
        )
    )

localizations/views.py
import logging

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
)
from geopy.geocoders import Nominatim

from events.views import MyListView
from localizations.forms import CommentForm
from localizations.forms import LocalizationAddressForm
from localizations.models import Comment
from localizations.models import Localization
from localizations.models import LocalizationAddress

logger = logging.getLogger(__name__)
geolocator = Nominatim(user_agent='gdziejestgrane')


class LocalizationCreateView(LoginRequiredMixin, CreateView):
    model = Localization
    fields = [
        'name',
        'sport_type',
        'localization_url',
        'picture'
    ]
    template_name = 'localizations/localizations-form.html'

    def get_success_url(self, *args, **kwargs):
        return reverse(
            'localizations-detail',
            kwargs={'pk': self.object.id}
        )


class LocalizationAddressCreateView(LoginRequiredMixin, CreateView):
    model = LocalizationAddress
    form_class = LocalizationAddressForm
    template_name = 'localizations/address-form.html'

    def get_success_url(self):
        return reverse(
            'localizations-detail',
            kwargs={'pk': self.object.id}
        )

    def post(self, request, *args, **kwargs):
        form = LocalizationAddressForm(request.POST)

        if not form.is_valid():
            super().post(request)
            return self.form_invalid(form)

        localization = Localization.objects.get(id=kwargs.get('pk'))
        address = form.save(commit=False)
        location = geolocator.geocode(address)
        address.lat, address.lon = location.latitude, location.longitude
        address.localization = localization
        logger.debug(localization)
        logger.debug(address.__dict__)
        address.save()

        return self.form_valid(form)


class LocalizationListView(ListView):
    model = Localization
    template_name = 'localizations/localizations-list.html'
    context_object_name = 'localizations'
    ordering = ['name']
    paginate_by = 6


class LocalizationDetailView(LoginRequiredMixin, DetailView, MyListView):
    context_object_name = "localization"
    model = Localization
    template_name = 'localizations/localizations-detail.html'

    def get_context_data(self, **kwargs):
        self.object_list = Comment.objects.filter(
            localization_id=self.object.id).order_by('-date_created')
        context = super().get_context_data(**kwargs)

        context['c_form'] = CommentForm(prefix='comment')

        context.update(
            self.pagination(
                "comments_",
                self.object_list,
                paginate_by=5
            )
        )

        return context

    def post(self, request, pk, *args, **kwargs):
        localization = self.get_object()
        user = request.user.id

        if request.is_ajax():
            if localization.likes.filter(id=user).exists():
                localization.likes.remove(user)
                like = False

            else:
                localization.likes.add(user)
                like = True

            return JsonResponse({
                "like": like
            })

        comment_form = CommentForm(request.POST, prefix='comment')
        if comment_form.is_valid():
            comment = Comment.objects.create(
                content=comment_form.cleaned_data["content"],
                user_id=user,
                localization_id=localization.id
            )
            comment.save()

            messages.success(request, _(f'Komentarz został utworzony'))

        return HttpResponseRedirect(
            reverse(
                'localizations-detail',
                kwargs={'pk': pk}
            )
        )


class MyLocalizationListView(LoginRequiredMixin, LocalizationListView):
    template_name = 'localizations/localizations-my.html'

    def get_queryset(self):
        return self.request.user.localization_set.all()


class CommentUpdateView(UpdateView, LoginRequiredMixin):
    model = Comment
    fields = ['content']
    template_name = 'localizations/comment-update.html'

    def get_success_url(self, *args, **kwargs):
        return reverse(
            'localizations-detail',
            kwargs={'pk': self.object.localization.id}
        )

    def get(self, request, pk, *args, **kwargs):
        if request.is_ajax():
            form = CommentForm(instance=Comment.objects.get(id=pk))
            html = render(
                request,
                'localizations/comment_form.html',
                {
                    'form': form
                }
            )

            return HttpResponse(html)


class CommentDeleteView(DeleteView, LoginRequiredMixin):
    model = Comment
    template_name = 'localizations/comment-delete.html'

    def get_success_url(self, *args, **kwargs):
        return reverse(
            'localizations-detail',
            kwargs={'pk': self.object.localization.id}
        )

localizations/templates/localizations/address-form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Dodaj adres{% endblock %}
{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block content %}
   <div class="container">
		<h5>Dodaj nowy adres</h5><hr><br>
		<div class="card">			
			<div class="card-body">				
				<form method="post">
					{% csrf_token %}
					{% bootstrap_form form %}
					<br>
                    <button class="btn btn-info btn-block btn-lg" type="submit">
                        Stwórz
                    </button>
				</form>
			</div>
		</div>
    </div>
{% endblock %}

localizations/templates/localizations/comment-delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %} Usuń {{ object.name}} {% endblock %}

{% block content %}
   <div class="container">        
		<div class="card">
			<div class="card-body">
                <h5>Czy na pewno chcesz usunąć {{object}}?</h5><hr><br>
                    <div class="row">

                        <div class="col-sm-6">
                            <form method="post">
                                {% csrf_token %}
                                <button class="btn btn-danger btn-block btn-lg" type="submit" value="Confirm">
                                    Tak
                                </button>
                            </form>
                        </div>

                        <div class="col-sm-6">
                            <a href="{% url 'localizations-detail' object.localization.id %}" >
                                <button class="btn btn-info btn-block btn-lg" value="Confirm">Nie</button>
                            </a>
                        </div>
                    </div>
			</div>
		</div>
    </div>
{% endblock %}

localizations/templates/localizations/comment-update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Edytuj komentarz{% endblock %}
{% block extrahead %}
{{ form.media }}
{% endblock %}

{% block content %}
   <div class="container">
        <h5>Edytuj komentarz</h5><hr><br>
        <div class="card">          
            <div class="card-body">             
                <form method="post">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <br>
                    <button class="btn btn-info btn-block btn-lg" type="submit">
                        Zaakceptuj zmiany
                    </button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

localizations/templates/localizations/comment_form.html
{% load bootstrap4 %}
{{ form.media }}
{% csrf_token %}
{% bootstrap_form form %}
<button class="btn btn-info btn-block btn-lg" type="submit">
    Zaakceptuj zmiany
</button>

localizations/templates/localizations/localizations-detail.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}
{% block extrahead %}
{{ form.media }}
{% endblock %}
{% block title %} Obiekt sportowy {{localization.name}} {% endblock %}

{% block content %}
    <!--  AJAX CSRF DJANGO DOCs -->
    <script src="{% static 'js/csrf.js' %}"></script>
    <!-- ajax like -->
    <script src="{% static 'localizations/js/main.js' %}"></script>


    <div class="container">

        <h5>Szczegóły obiektu</h5><hr><br>

        <!-- <div class="event"> -->
        <div class="row">
            <div class="col-sm-7">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-61">
                            <img class='card-img-top' src="{{localization.picture.url}}" alt="Localization Photo">
                            </div>
                            <div class="col-sm-61">
                                <p class="card-text">
                                <h6>{{ localization.name }}</h6>
                                <ul>
                                    <li>Dyscyplina: <strong>{{ localization.get_sport_type_display }}</strong></li>
                                    <li>Lokalizacja:
                                        {% if localization.localizationaddress %}
                                        <strong>
                                            {{ localization.localizationaddress }}
                                        </strong>
                                        {% else %}
                                        <a href="{% url 'localizations-address-create' localization.id %}">
                                        <button class="badge badge-pill badge-light">Dodaj adres</button>
                                        </a>
                                        {% endif %}
                                    </li>
                                    <li>Liczba polubień: <strong><span id='like-count-span'>{{ localization.likes.count }}</span></strong></li>
                                    <li>Link: <strong><a href="{{ localization.localization_url }}" target="_blank">{{ localization.localization_url }}</a></strong></li>
                                </ul>

                                <!-- <div class="event_button"> -->
                                    <form method ='post' class= 'like-button-form'>
                                        {% csrf_token %}
                                        <button class="btn btn-success btn-block" id='like-button' type="submit"
                                        {% if user.is_authenticated and user not in localization.likes.all %}
                                        style="display: block-inline;"
                                        {% else %}
                                        style="display: none;"
                                        {% endif %}
                                        name="like-button" value="like-button">
                                            Oceń pozytywnie
                                        </button>

                                        <button class="btn btn-danger btn-block" id='dislike-button' type="submit"
                                        {% if user.is_authenticated and user not in localization.likes.all %}
                                        style="display: none;"
                                        {% else %}
                                        style="display: block-inline;"
                                        {% endif %}
                                        >Oceń negatywnie
                                        </button>
                                    </form>
                                <!-- </div>  -->
                                {% if user in admins %}
                                <br><div class="row">
                                    <div class="col-sm-6">
                                        <a href="{% url 'localizations-update' localization.id %}">
                                        <button class="btn btn-info btn-block btn-sm">Edytuj</button>
                                        </a>
                                    </div>
                                    <div class="col-sm-6">
                                        <a href="{% url 'localizations-delete' localization.id %}">
                                        <button class="btn btn-danger btn-block btn-sm">Usuń</button>
                                        </a>
                                    </div>
                                </div>
                                {% else %}
                                {% endif %}
                                </p>
                            </div>
                        </div>
                    </div>
                </div><br>
            </div>
            <div class="col-sm-5">
                <div class="card">
                    <div class="card-body">
                        <h6>Komentarze</h6>

                        <form method="post">
                          {% csrf_token %}
                          {% bootstrap_form c_form %}
                          <button class="btn btn-info btn-block" type="submit" name="comment" value="comment">Dodaj</button>
                        </form>

                        <br><p>Liczba wszystkich komentarzy: <strong>{{ comments_paginator.count }}</strong></p>

                        {% for comment in comments_object_list %}
                        <div class="card bg-light text-dark">
                            <div class="card-body">
                            <p>{{ comment.user }} - {{ comment.date_created }}</p>
                            <p><strong>{{ comment.content }}</strong></p>
                            {% if user.id == comment.user_id %}
                            <div class="row">
                                <div class="col-sm-6">

                                <button class="btn btn-outline-secondary btn-sm edit" type="button" data-toggle="modal"
                                        data-href="{% url 'comment-update' comment.id %}" value="{{ comment.id }}" data-target="#Modal1EdytujKom{{ comment.id }}">Edytuj</button>
                                <div class="modal" id="Modal1EdytujKom{{ comment.id }}" tabindex="-1" role="dialog">
                                    <div class="modal-dialog modal-dialog-centered" role="document">
                                      <div class="modal-content">
                                        <div class="modal-header">
                                          <h4 class="modal-title">Edytuj komentarz</h4>
                                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">×</span>
                                          </button>
                                        </div>
                                        <div class="modal-body">
                                            <form method="post" action="{% url 'comment-update' comment.id %}" id="commentForm{{ comment.id }}">
                                            </form>
                                        </div>
                                      </div>
                                    </div>
                                </div>

                                </div>
                                <div class="col-sm-6">
                                    <button class="btn btn-outline-danger btn-sm" type="button" data-toggle="modal" data-target="#Modal1UsunKom{{ comment.id }}">Usuń</button>
                                    <div class="modal" id="Modal1UsunKom{{ comment.id }}" tabindex="-1" role="dialog">
                                        <div class="modal-dialog modal-dialog-centered" role="document">
                                          <div class="modal-content">
                                            <div class="modal-header">
                                              <h4 class="modal-title">Czy na pewno chcesz usunąć komentarz?</h4>
                                              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">×</span>
                                              </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">
                                                    <div class="col-sm-6">
                                                    <form method="post" action="{% url 'comment-delete' comment.id %}">
                                                        {% csrf_token %}
                                                        <button class="btn btn-danger btn-block" type="submit" value="Confirm">Tak</button>
                                                    </form>
                                                    </div>
                                                    <div class="col-sm-6">
                                                        <button class="btn btn-info btn-block" data-dismiss="modal">Nie</button>
                                                    </a>
                                                    </div>
                                                </div>
                                            </div>
                                          </div>
                                        </div>
                                    </div>
                                <!-- </form> -->
                                </div>
                            </div>
                            {% endif %}
                            </div>
                        </div><br>
                        {% empty %}
                        <p>Brak komentarzy</P>
                        {% endfor %}

                        {% with pagination_prefix='comments_' page_obj=comments_page_obj paginator=comments_paginator is_paginated=comments_is_paginated object_list=comments_object_list page='comments_page' %}
                            {% include 'includes/django-filter-pagination.html' %}
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %} 

localizations/templates/localizations/localizations-form.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block title %}Stwórz Lokalizacje{% endblock %}
{% block extrahead %}
{{ form.media }}
{% endblock %}
{% block content %}
   <div class="container">
		<h5>Dodaj nowy obiekt</h5><hr><br>
		<div class="card">			
			<div class="card-body">
				<form method="post" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="row">
						<div class="col-sm-4">
						  {% bootstrap_field form.name %}
						</div>
						<div class="col-sm-4">
						  {% bootstrap_field form.sport_type %}
						</div> 	
						<div class="col-sm-4">
						  {% bootstrap_field form.localization_url %}
						</div>
						<div class="col-sm-4">
						  {% bootstrap_field form.picture %}
						</div>
					 </div>
					 <br>
                    <button class="btn btn-info btn-block btn-lg" type="submit">
                        Stwórz
                    </button>
				</form>
			</div>
		</div>
    </div>
{% endblock %}

localizations/templates/localizations/localizations-list.html
{% extends 'base.html' %}
{% block title %} Lokalizacje {% endblock %}

{% block content %}
    <div class="container">
        <h5>Lista obiektów</h5><hr><br>
        <div class='card-columns'>
            {% for localization in localizations %}
                <div class="card bg-light">
                    <img class='card-img-top' src="{{localization.picture.url}}" alt="Event Photo">
                    <div class="card-body">
                        <h6 class='card-title'>
                            {{ localization.name }}
                        </h6><hr>
                        <p class="card-text">
                            {{ localization.localizationaddress }}
                        </p>
                        <a href="{% url 'localizations-detail' localization.id %}" class='btn btn-info btn-block'>
                            Szczegóły
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    {% include 'includes/pagination.html' %}

{% endblock %}

localizations/templates/localizations/localizations-my.html
{% extends 'base.html' %}
{% block title %} Moje obiekty {% endblock %}

{% block content %}
    <div class="container">
    <h5> Twoje ulubione obiekty </h5><hr><br>
        <div class='card-columns'>
            {% for localization in localizations %}
                <div class="card bg-light">
                    <img class='card-img-top' src="{{localization.picture.url}}" alt="Event Photo">
                    <div class="card-body">
                        <h6 class='card-title'>
                            {{ localization.name }}
                        </h6><hr>
                        <p class="card-text">
                            {{ localization.localizationaddress }}
                        </p>
                        <a href="{% url 'localizations-detail' localization.id %}" class='btn btn-info btn-block'>
                            Szczegóły
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
  
    {% include 'includes/pagination.html' %}

{% endblock %}